import type { Referee } from "./types";

type RefereeRaw = Omit<Referee, 'totalMilesTravelled' | 'mostCommonTeams' | 'daysWorkedStreak'>;

export const referees: RefereeRaw[] = [
  {
    id: 'ref-001',
    name: 'James Mitchell',
    games: [
      {
        id: 'game-001',
        date: '2024-02-03',
        location: 'Chapel Hill, NC',
        coordinates: [35.9132, -79.0558],
        homeTeam: { name: 'Tar Heels', location: 'UNC' },
        awayTeam: { name: 'Blue Devils', location: 'Duke' },
      },
      {
        id: 'game-002',
        date: '2024-02-10',
        location: 'New York, NY',
        coordinates: [40.7128, -74.006],
        homeTeam: { name: 'Wildcats', location: 'St. John\'s' },
        awayTeam: { name: 'Hoyas', location: 'Georgetown' },
      },
      {
        id: 'game-003',
        date: '2024-02-17',
        location: 'Boston, MA',
        coordinates: [42.3601, -71.0589],
        homeTeam: { name: 'Eagles', location: 'Boston College' },
        awayTeam: { name: 'Huskies', location: 'UConn' },
      },
      {
        id: 'game-004',
        date: '2024-02-24',
        location: 'Philadelphia, PA',
        coordinates: [39.9526, -75.1652],
        homeTeam: { name: 'Wildcats', location: 'Villanova' },
        awayTeam: { name: 'Owls', location: 'Temple' },
      },
      {
        id: 'game-005',
        date: '2024-03-02',
        location: 'Durham, NC',
        coordinates: [35.994, -78.8986],
        homeTeam: { name: 'Blue Devils', location: 'Duke' },
        awayTeam: { name: 'Wolfpack', location: 'NC State' },
      },
    ],
  },
  {
    id: 'ref-002',
    name: 'Sandra Williams',
    games: [
      {
        id: 'game-006',
        date: '2024-02-05',
        location: 'Los Angeles, CA',
        coordinates: [34.0522, -118.2437],
        homeTeam: { name: 'Bruins', location: 'UCLA' },
        awayTeam: { name: 'Trojans', location: 'USC' },
      },
      {
        id: 'game-007',
        date: '2024-02-12',
        location: 'Berkeley, CA',
        coordinates: [37.8716, -122.2727],
        homeTeam: { name: 'Golden Bears', location: 'Cal' },
        awayTeam: { name: 'Cardinal', location: 'Stanford' },
      },
      {
        id: 'game-008',
        date: '2024-02-19',
        location: 'Chicago, IL',
        coordinates: [41.8781, -87.6298],
        homeTeam: { name: 'Illini', location: 'Illinois' },
        awayTeam: { name: 'Wildcats', location: 'Northwestern' },
      },
      {
        id: 'game-009',
        date: '2024-02-26',
        location: 'Houston, TX',
        coordinates: [29.7604, -95.3698],
        homeTeam: { name: 'Cougars', location: 'Houston' },
        awayTeam: { name: 'Mean Green', location: 'North Texas' },
      },
      {
        id: 'game-010',
        date: '2024-03-04',
        location: 'Atlanta, GA',
        coordinates: [33.749, -84.388],
        homeTeam: { name: 'Yellow Jackets', location: 'Georgia Tech' },
        awayTeam: { name: 'Bulldogs', location: 'Georgia' },
      },
    ],
  },
  {
    id: 'ref-003',
    name: 'Carlos Rivera',
    games: [
      {
        id: 'game-011',
        date: '2024-02-06',
        location: 'Durham, NC',
        coordinates: [35.994, -78.8986],
        homeTeam: { name: 'Blue Devils', location: 'Duke' },
        awayTeam: { name: 'Tar Heels', location: 'UNC' },
      },
      {
        id: 'game-012',
        date: '2024-02-13',
        location: 'Chicago, IL',
        coordinates: [41.8781, -87.6298],
        homeTeam: { name: 'Ramblers', location: 'Loyola Chicago' },
        awayTeam: { name: 'Redbirds', location: 'Illinois State' },
      },
      {
        id: 'game-013',
        date: '2024-02-20',
        location: 'Atlanta, GA',
        coordinates: [33.749, -84.388],
        homeTeam: { name: 'Eagles', location: 'Morehouse' },
        awayTeam: { name: 'Tigers', location: 'Clark Atlanta' },
      },
      {
        id: 'game-014',
        date: '2024-02-27',
        location: 'Los Angeles, CA',
        coordinates: [34.0522, -118.2437],
        homeTeam: { name: 'Bruins', location: 'UCLA' },
        awayTeam: { name: 'Waves', location: 'Pepperdine' },
      },
    ],
  },
];
